name: Test Pinned Dependencies on GPU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    name: Build wheel and test
    defaults:
      run:
        # Required when using an activated conda environment in steps
        # See https://github.com/conda-incubator/setup-miniconda#IMPORTANT
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@main

      - uses: conda-incubator/setup-miniconda@v3
        name: Setup conda environment
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: paste
          environment-file: environment.yml

      - name: Install package
        # Note: editable install for the coverage step to pick up source
        # correctly. (coverage run --source=src/paste3 -m pytest)
        run: pip install .

      - name: Check Versions of Dependencies
        run: pip freeze

      - name: Pytest
        run: pytest
