name: Test Unpinned Dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, vb/napari_enhancements ]

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Developer Dependencies
        run: pip install .[dev]

      - name: List dependencies
        run: pip freeze

      - name: Pytest
        run: pytest -n auto
